[project]
name = "pypboy-ng"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "pygame>=2.6.1",
    "requests>=2.32.5",
    "xmltodict>=1.0.2",
]
